name: stillnote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6
  file_picker: ^10.1.2
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.10+1
  go_router: ^15.0.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  scrollable_positioned_list: ^0.3.8
  # share_plus_dialog:
  url_strategy: ^0.3.0
  youtube_player_iframe: ^5.1.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  firebase_storage: ^12.4.5
  cross_file: ^0.3.4+1
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  code_text_field: ^1.1.0
  video_player: ^2.8.6
  flick_video_player: ^0.9.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: '#FFFFFF'
  color_dark: '#494949'
  image: assets/images/app_icon_black.png
  image_dark: assets/images/app_icon_white.png
  web_image_mode: center
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

  android_12:
    color: '#FFFFFF'
    color_dark: '#494949'
    image: assets/images/app_icon_black.png
    image_dark: assets/images/app_icon_white.png